name: dotnet-format-validation

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100'
        include-prerelease: true
    - name: build
      run: dotnet build
    - name: check format
      run: dotnet format --verify-no-changes
